name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.1', '8.2']
        laravel: ['10', '11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Laravel 10
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:10.*" --no-update --no-interaction
        if: "matrix.laravel == '10' && (matrix.php == '8.1' || matrix.php == '8.2')"

      - name: Select Laravel 11
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:11.*" --no-update --no-interaction
        if: "matrix.laravel == '11' && matrix.php == '8.2'"

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress --ignore-platform-req=php

      - name: Execute PHPUnit
        run: vendor/bin/phpunit