name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3']
        laravel: ['10', '11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Laravel ${{ matrix.laravel }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-update --no-interaction

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress --ignore-platform-req=php

      - name: Run tests for Laravel ${{ matrix.laravel }}
        run: vendor/bin/phpunit
